name: world_of_knowledge
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-285.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.5
  scroll_snap_list: ^0.9.1
  google_fonts: ^4.0.3
  flutter_scale_tap: ^1.0.5
  shared_preferences: ^2.1.0
  markdown_viewer: ^0.5.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/planets/
    - images/background/
    - images/buttons/
    - images/planets/persons/
    - images/story/cover/
    - images/story/image/
    - images/video/
  # To add assets to your application, add an assets section, like this:


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
